name: Update NASA Image

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Python 버전 명시

      - name: Install dependencies
        run: pip install -r requirements.txt  # Pip 업그레이드 생략

      - name: Execute script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python _code/NASA_API/update_nasa_image.py  # 정확한 실행 경로 지정
